name: 'Testplane action'
description: 'GitHub action for Testplane'
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  cwd:
    description: 'Relative directory to run Testplane in'
    required: false
    default: '.'
  package-manager:
    description: 'Package manager, used in the project (one of "npm", "pnpm", "yarn")'
    required: false
    default: 'npm'
  html-report-prefix:
    description: 'Html-reporter report path prefix'
    required: false
    default: 'testplane-reports'
  config-path:
    description: 'Testplane custom config path'
    required: false
    default: ''
  storybook:
    description: 'If enabled, uses @testplane/storybook plugin tests'
    required: false
    default: ''
  set:
    description: 'Comma separated list of sets to test'
    required: false
    default: ''
  browser:
    description: 'Comma separated list of browsers to test'
    required: false
    default: ''
  grep:
    description: 'Grep expression to specify tests to launch'
    required: false
    default: ''
outputs:
  html-report-path:
    description: 'Path to html report, generated by html-reporter'
  exit-code:
    description: 'Testplane run exit code'
